---
build_targets:
    linux32: Linux_x86-gcc3
    linux64: Linux_x86_64-gcc3
    win32: WINNT_x86-gcc3
    osx32: Darwin_x86-gcc3
channels:
    alpha: 6.5n
    nightly: 6.4n
    release: 6.3n
versions:
    6.5n:
        platformVersion: 45.8.0
        detailsURL: https://yoursite/projects/torbrowser.html.en
        download_url: https://yoursite/dist/torbrowser/alpha/6-5n
    
    6.4n:
        platformVersion: 45.8.0
        detailsURL: https://yoursite/projects/torbrowser.html.en
        download_url: https://yoursite/dist/torbrowser/nightly/6-5n
    
    6.3n:
        platformVersion: 45.8.0
        detailsURL: https://yoursite/projects/torbrowser.html.en
        download_url: https://yoursite/dist/torbrowser/release/6-5n

