---
releases_dir:  /var/www/torupdates/htdocs/releases
download:
    archive_url: https://jondobrowser.jondos.de/releases
    gpg_keyring: kaitian.gpg
    bundles_url: https://jondobrowser.jondos.de/releases
    mars_url: https://jondobrowser.jondos.de/releases
build_targets:
    linux32: Linux_x86-gcc3
    linux64: Linux_x86_64-gcc3
    win32:
        - WINNT_x86-gcc3
        - WINNT_x86-gcc3-x86
        - WINNT_x86-gcc3-x64
    win64:
        - WINNT_x86_64-gcc3-x64
    osx32: Darwin_x86-gcc3
    osx64: Darwin_x86_64-gcc3
channels:
    alpha: 7.5a9.1.5
    product: 7.5.9.14
versions:
    7.5a9.1.5:
        platformVersion: 52.5.1
        detailsURL: https://jondobrowser.jondos.de/blog/jondobrowser-released/alpha/
        incremental_from:
        migrate_archs:
          osx32: osx64
    7.5.9.14:
        platformVersion: 52.5.1
        detailsURL: https://jondobrowser.jondos.de/blog/jondobrowser-released/product/
        incremental_from:
        migrate_archs:
          osx32: osx64          