---
releases_dir:  /var/www/torupdates/htdocs/jondobrowser
download:
    archive_url: https://jondobrowser.jondos.de/jondobrowser
    gpg_keyring: kaitian.gpg
    bundles_url: https://jondobrowser.jondos.de/jondobrowser
    mars_url: https://jondobrowser.jondos.de/jondobrowser
build_targets:
    linux32: Linux_x86-gcc3
    linux64: Linux_x86_64-gcc3
    win32:
        - WINNT_x86-gcc3
        - WINNT_x86-gcc3-x86
        - WINNT_x86-gcc3-x64
    osx32: Darwin_x86-gcc3
    osx64: Darwin_x86_64-gcc3
channels:
    alpha: 7.5a1.1
    #release: 7.5a1
    #nightly: 7.5a1
versions:
    7.5a1.1:
        platformVersion: 52.2.0
        detailsURL: https://jondobrowser.jondos.de/blog/jondobrowser-released/
        incremental_from:
          - 7.0a3
          - 7.5a1
        migrate_archs:
          osx32: osx64